name: Docker Hub

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: deploy-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUBDZ }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dz-bot:latest

  deploy_on_remote_server:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Load Docker image on remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -vvv ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
            # if github repo is not cloned on remote server then clone it
            if [ ! -d "/home/${{ secrets.REMOTE_SERVER_USERNAME }}/dz-bot" ]; then
              git clone https://github.com/deathzombee/Dz-bot.git /home/${{ secrets.REMOTE_SERVER_USERNAME }}/dz-bot
              cd /home/${{ secrets.REMOTE_SERVER_USERNAME }}/dz-bot
            else
              cd /home/${{ secrets.REMOTE_SERVER_USERNAME }}/dz-bot
              git pull
            fi
        
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dz-bot:latest
            docker stop dz-bot || true
            docker rm dz-bot || true
            docker compose up -d  
          ENDSSH
